version: '3.8'

services:
  newapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_NEWS_API_KEY: ${REACT_APP_NEWS_API_KEY}
        REACT_APP_GUARDIAN_API_KEY: ${REACT_APP_GUARDIAN_API_KEY}
        REACT_APP_NYT_API_KEY: ${REACT_APP_NYT_API_KEY}
    container_name: newapp-container
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_NEWS_API_KEY=${REACT_APP_NEWS_API_KEY}
      - REACT_APP_GUARDIAN_API_KEY=${REACT_APP_GUARDIAN_API_KEY}
      - REACT_APP_NYT_API_KEY=${REACT_APP_NYT_API_KEY}
    env_file:
      - .env
